<?php

namespace App\Tests\Functional\Controller\RestaurantManager;

use App\Services\Restaurant\RestaurantBuilder;
use App\Services\Restaurant\RestaurantProvider;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class RestaurantManagerControllerTest extends WebTestCase
{
    private KernelBrowser $client;
    private string $filePath;
    private RestaurantProvider $restaurantProvider;

    static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public function setUp(): void
    {
        $this->client = static::createClient();
        $em = $this->getContainer()->get(EntityManagerInterface::class);
        $restaurantBuilder = new RestaurantBuilder($em);
        $this->restaurantProvider = new RestaurantProvider($restaurantBuilder, $em);
        $this->filePath = realpath(__DIR__ . '/../../../..') . $_ENV['FILE_PATH'];
        if (file_exists($this->filePath)) {
            unlink($this->filePath);
        }
    }

    public function tearDown(): void
    {
        if (file_exists($this->filePath)) {
            unlink($this->filePath);
        }
        parent::tearDown();
    }

    public function testOpenRestaurant(): void
    {
        $this->client->request('GET', '/restaurant/open/1');
        $this->assertResponseIsSuccessful();
    }

    public function testRestaurantNotFound(): void
    {
        $this->client->request('GET', '/restaurant/close');
        $content = $this->client->getResponse()->getContent();

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Restaurant not found!', $content);
    }

    public function testRestaurantClosed(): void
    {
        $this->restaurantProvider->getRestaurant(1);
        $this->client->request('GET', '/restaurant/close');
        $content = $this->client->getResponse()->getContent();

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Restaurant closed!', $content);
    }
}
