# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\DataFixtures\MenuFixture:
        tags: ['doctrine.fixture.orm']

    App\Services\Payment\CashPaymentProcessor:
        tags:
            - {name: 'paymentStrategies', key: 'cashPayment'}

    App\Services\Payment\CardPaymentProcessor:
        tags:
            - { name: 'paymentStrategies', key: 'cardPayment' }

    App\Services\Payment\TipsCardPaymentDecorator:
        tags:
            - { name: 'paymentStrategies', key: 'tipsCardPayment' }

    App\Services\Payment\TipsCashPaymentDecorator:
        tags:
            - { name: 'paymentStrategies', key: 'tipsCashPayment' }

    App\Services\Payment\PaymentHandler:
        arguments: [!tagged_locator { tag: 'paymentStrategies', index_by: 'key' }]

    App\Services\Client\ClientFactory:
        arguments: [!tagged_iterator { tag: 'paymentStrategies', index_by: 'key' }]

    App\EventListener\Waiter\WaiterListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'postUpdate', entity: 'App\Entity\Client', method: 'processOrderByWaiter'}
            - { name: 'doctrine.orm.entity_listener', event: 'postUpdate', entity: 'App\Entity\Order', method: 'deliveryOrder' }

    App\EventListener\Kitchener\KitchenerListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'postUpdate', entity: 'App\Entity\Order', method: 'processOrderByKitchen' }

    App\EventListener\Client\ClientListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'postPersist', entity: 'App\Entity\Client', method: 'makeOrder'}

    App\EventListener\Order\OrderListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'postUpdate', entity: 'App\Entity\Order', method: 'payOrder'}